/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/albums': RouteRecordInfo<
      '/albums',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bar': RouteRecordInfo<
      '/bar',
      '/bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos': RouteRecordInfo<
      '/demos',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media': RouteRecordInfo<
      '/media',
      '/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photos': RouteRecordInfo<
      '/photos',
      '/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/deepClone': RouteRecordInfo<
      '/posts/deepClone',
      '/posts/deepClone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git-exp': RouteRecordInfo<
      '/posts/git-exp',
      '/posts/git-exp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/iife': RouteRecordInfo<
      '/posts/iife',
      '/posts/iife',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/js-pre-compilation': RouteRecordInfo<
      '/posts/js-pre-compilation',
      '/posts/js-pre-compilation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/promise': RouteRecordInfo<
      '/posts/promise',
      '/posts/promise',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sse': RouteRecordInfo<
      '/posts/sse',
      '/posts/sse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/undefined': RouteRecordInfo<
      '/posts/undefined',
      '/posts/undefined',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects': RouteRecordInfo<
      '/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/albums.md': {
      routes:
        | '/albums'
      views:
        | never
    }
    'pages/bar.md': {
      routes:
        | '/bar'
      views:
        | never
    }
    'pages/demos.md': {
      routes:
        | '/demos'
      views:
        | never
    }
    'pages/media.md': {
      routes:
        | '/media'
      views:
        | never
    }
    'pages/notes.md': {
      routes:
        | '/notes'
      views:
        | never
    }
    'pages/photos.md': {
      routes:
        | '/photos'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/deepClone.md': {
      routes:
        | '/posts/deepClone'
      views:
        | never
    }
    'pages/posts/git-exp.md': {
      routes:
        | '/posts/git-exp'
      views:
        | never
    }
    'pages/posts/iife.md': {
      routes:
        | '/posts/iife'
      views:
        | never
    }
    'pages/posts/js-pre-compilation.md': {
      routes:
        | '/posts/js-pre-compilation'
      views:
        | never
    }
    'pages/posts/promise.md': {
      routes:
        | '/posts/promise'
      views:
        | never
    }
    'pages/posts/sse.md': {
      routes:
        | '/posts/sse'
      views:
        | never
    }
    'pages/posts/undefined.md': {
      routes:
        | '/posts/undefined'
      views:
        | never
    }
    'pages/projects.md': {
      routes:
        | '/projects'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
